telegram:
  ip: 222.222.222.222
  port: 88
  key: "private.key"
  cert: "cert.pem"
mqtt:
  server: 192.168.1.100
  username: "username"
  password: "password"
  enable: true
cameras:
  yicam-1:
    topics:
      - "yicam-1/status"
      - "yicam-1/motion_detection_image"
    ip: 192.168.1.1
  yicam-2:
    topics:
      - "yicam-2/status"
      - "yicam-1/motion_detection_image"
    ip: 192.168.1.2
token: code
users:
  TelegramUsername:
    cameras: #ACL
      - yicam-1
      - yicam-2
admin: TelegramUsername