telegram:
  ip: 2.2.2.2
  port: 88
  key: "private.key"
  cert: "cert.pem"
broker-mqtt:
  ip: 192.168.1.1 #Leave empty if not used
  username: "mqtt-user"
  password: "password"
  enable: true
cameras:
  yicam-1:
    type: yi-hack-allwinner
    ip: 192.168.1.192
    port: 80
    ping-time: 10 # Ping camera every x seconds
    topics: # See camera types topics
      - status-message
      - motion-message
      - motion-image
      - sound-message
    username: username
    password: password
  reolink-1:
    type: reolink-4k
    ip: 192.168.1.190
    port: 80
    ping-time: 10
    username: username
    password: password
token: 1234523:2342525234523424234234324
users:
  Username:
    cameras:
      - yicam-1
      - reolink-1
admin: Username