telegram:
  ip: 2.2.2.2
  port: 88
  key: "private.key"
  cert: "cert.pem"
broker-mqtt:
  ip: 192.168.1.1 #Leave empty if not used
  username: "mqtt-user"
  password: "password"
  enable: true
cameras:
  yicam-1:
    snapshot: "/cgi-bin/snapshot.sh"
    video: "/cgi-bin/getlastrecordedvideo.sh?oldness=0&type=4"
    speak: "/cgi-bin/speak.sh?lang=it-IT"
    speaker: "/cgi-bin/speaker.sh"
    type: "yi-hack-allwinner"
    topics:
      - "yicam-1/status"
      - "yicam-1/motion_detection_image"
    ip-port: 192.168.1.192:80
  yicam-2:
    snapshot: "/cgi-bin/snapshot.sh"
    video: "/cgi-bin/getlastrecordedvideo.sh?oldness=0&type=4"
    speak: "/cgi-bin/speak.sh?lang=it-IT"
    speaker: "/cgi-bin/speaker.sh"
    type: "yi-hack-allwinner"
    topics:
      - "yicam-2/status"
      - "yicam-1/motion_detection_image"
    ip-port: 192.168.1.193:80
token: 1234523:2342525234523424234234324
users:
  Username:
    cameras:
      - yicam-1
      - yicam-2
admin: Username