version: "3.9"

services:
  yi-home-control-bot:
    build: .
    image: yi_home_control_bot_image
    container_name: yi_home_control_bot_cont
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
